[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeline-helper"
version = "0.3.1"
dependencies = [
    "uvloop~=0.21.0",
    "aio_pika~=9.4.1",
    "aiormq~=6.8.0",
]

[tool.setuptools]
packages = [
    "pipeline",
]
